// ============================================================
//  DARWASH · INICIO — frases del día
//  Una por día, la misma para todo el equipo (rota sola).
//  Formato: [frase, autor]  · autor "" = frase del grupo
//  Para agregar: sumá líneas al array y pusheá. No hace falta subir version.
// ============================================================
window.DW_FRASES = [
  // ---------- Martín Fierro (José Hernández, 1872/1879) ----------
  ["Los hermanos sean unidos, porque ésa es la ley primera; tengan unión verdadera en cualquier tiempo que sea, porque si entre ellos pelean los devoran los de ajuera.", "Martín Fierro"],
  ["Debe trabajar el hombre para ganarse su pan; pues la miseria, en su afán de perseguir de mil modos, llama en la puerta de todos y entra en la del haragán.", "Martín Fierro"],
  ["Muchas cosas pierde el hombre que a veces las vuelve a hallar; pero les debo enseñar, y es bueno que lo recuerden: si la vergüenza se pierde, jamás se vuelve a encontrar.", "Martín Fierro"],

  // ---------- Refranes y dichos ----------
  ["El ojo del amo engorda el ganado.", "Refrán popular"],
  ["En la cancha se ven los pingos.", "Dicho criollo"],
  ["A quien madruga, Dios lo ayuda.", "Refrán popular"],
  ["La unión hace la fuerza.", "Refrán popular"],
  ["Poco a poco se anda lejos.", "Refrán popular"],
  ["Más vale maña que fuerza.", "Refrán popular"],
  ["Al mal tiempo, buena cara.", "Refrán popular"],
  ["Cuatro ojos ven más que dos.", "Refrán popular"],
  ["Quien bien siembra, bien cosecha.", "Refrán popular"],
  ["Grano a grano llena la gallina el buche.", "Refrán popular"],
  ["Del dicho al hecho hay mucho trecho.", "Refrán popular"],
  ["No dejes para mañana lo que puedas hacer hoy.", "Refrán popular"],
  ["Hombre prevenido vale por dos.", "Refrán popular"],
  ["Más vale prevenir que curar.", "Refrán popular"],
  ["El que la sigue, la consigue.", "Refrán popular"],
  ["Querer es poder.", "Refrán popular"],
  ["No hay mal que por bien no venga.", "Refrán popular"],
  ["Camarón que se duerme se lo lleva la corriente.", "Refrán popular"],
  ["Una golondrina no hace verano.", "Refrán popular"],
  ["Despacito y buena letra.", "Refrán popular"],
  ["Más sabe el diablo por viejo que por diablo.", "Refrán popular"],
  ["Haz el bien y no mires a quién.", "Refrán popular"],
  ["Más vale tarde que nunca.", "Refrán popular"],
  ["A caballo regalado no se le miran los dientes.", "Refrán popular"],
  ["Caminante, no hay camino: se hace camino al andar.", "Antonio Machado"],

  // ---------- Del grupo: equipo ----------
  ["Tropa que se carga en equipo, llega mejor.", ""],
  ["Nadie arrea solo: el que va adelante abre la tranquera, el que va atrás junta la que se abre.", ""],
  ["Un remate sale bien cuando cada uno hace bien su parte, aunque nadie la vea.", ""],
  ["El mejor equipo no es el que nunca se equivoca, es el que se avisa a tiempo.", ""],
  ["Una mano lava la otra, y las dos lavan la cara. Así trabajamos acá.", ""],
  ["Si sabés algo que al de al lado le sirve, contáselo. El conocimiento también se reparte como el pasto.", ""],
  ["Ayudar al compañero no te atrasa: nos adelanta a todos.", ""],
  ["En este grupo, el problema de uno es la tarea de todos.", ""],
  ["La feria, el feedlot y el campo son tres lugares, pero un solo equipo.", ""],
  ["Darwash, El Garabí y Bulltrade: tres marcas, una misma camiseta.", ""],
  ["Un buen mate compartido arregla más cosas que diez mails.", ""],
  ["Pedir ayuda no es debilidad: es no dejar que el error se agrande.", ""],
  ["Lo que hace uno suma; lo que hacemos juntos multiplica.", ""],
  ["Preguntá antes de suponer. Nos ahorra a todos un viaje de vuelta.", ""],
  ["El que avisa no traiciona: un aviso a tiempo vale más que una disculpa tarde.", ""],
  ["Nadie conoce todos los corrales, pero entre todos conocemos el campo entero.", ""],
  ["Las tropas grandes se mueven con muchos jinetes.", ""],
  ["Que el compañero nuevo se sienta en casa: todos fuimos nuevos alguna vez.", ""],
  ["Un gracias a tiempo vale más que un aumento de kilos.", ""],
  ["Cuando uno flojea, el equipo empuja. Mañana capaz te toca empujar a vos.", ""],

  // ---------- Del grupo: trabajo y oficio ----------
  ["El campo no espera: se trabaja con lo que hay y se mejora lo que se puede.", ""],
  ["Hoy también hay alguien en el corral que hace la diferencia. Que seas vos.", ""],
  ["La hacienda bien tratada pesa más. La gente también.", ""],
  ["Cada DTE en orden es una preocupación menos para mañana.", ""],
  ["El que anota bien en la manga, no corre después en la oficina.", ""],
  ["Los kilos se hacen día a día, igual que los resultados.", ""],
  ["Una liquidación prolija dice más de nosotros que cualquier publicidad.", ""],
  ["El productor vuelve por el precio, pero se queda por la confianza.", ""],
  ["La palabra dada en la feria vale como una firma. Cuidémosla.", ""],
  ["Hacer las cosas bien cuando nadie mira: eso es oficio.", ""],
  ["El detalle que hoy parece chico es el reclamo que mañana no llega.", ""],
  ["Ordenar hoy es ganar tiempo mañana.", ""],
  ["No hay remate fácil: hay remates bien preparados.", ""],
  ["El feedlot enseña paciencia: nada engorda de un día para el otro.", ""],
  ["La calidad no se improvisa en la balanza: se construye en cada día de corral.", ""],
  ["Lo que se mide, se mejora. Lo que se anota, no se olvida.", ""],
  ["Un número bien cargado ahorra diez llamados.", ""],
  ["El que conoce la hacienda, la vende mejor.", ""],
  ["Atender bien al que llama es parte del negocio, no una interrupción.", ""],
  ["La confianza se gana en años y se pierde en un rato. Cuidemos cada operación.", ""],
  ["Trabajar con prolijidad también es una forma de respeto.", ""],
  ["Si algo se puede automatizar, que trabaje la máquina y piense la persona.", ""],
  ["El que aprende algo nuevo cada semana, al año es otro.", ""],
  ["Una buena tropa empieza mucho antes de subir al camión.", ""],
  ["Cumplir los plazos es cumplirle a alguien que está esperando.", ""],
  ["Las cosas bien hechas no necesitan explicación.", ""],
  ["Escuchar al productor es la mitad de la venta.", ""],
  ["En el campo se aprende que el apuro y la prisa no son lo mismo.", ""],
  ["Hay que saber leer el cielo, el mercado y a la gente.", ""],

  // ---------- Del grupo: ánimo ----------
  ["Al que le toca el día difícil, que sepa que no está solo.", ""],
  ["La lluvia no se elige, pero cómo la recibimos, sí.", ""],
  ["Los años malos también enseñan; los buenos se festejan juntos.", ""],
  ["Cada día de trabajo es una tranquera que se abre.", ""],
  ["Arrancá por lo más difícil: el resto del día va a parecer una siesta.", ""],
  ["Un error es una lección con mala prensa.", ""],
  ["El campo premia al constante más que al apurado.", ""],
  ["Sembrar es confiar en lo que todavía no se ve.", ""],
  ["Que el cansancio sea de haber hecho, no de haber esperado.", ""],
  ["Hoy es un buen día para hacer algo de lo que mañana estés orgulloso.", ""],
  ["No hace falta ser el más rápido: alcanza con no aflojar.", ""],
  ["Las ganas también se contagian. Arrancá vos.", ""],
  ["El que se ríe en la oficina trabaja mejor. Comprobado en el corral.", ""],
  ["Después de la sequía siempre llueve. Hay que estar listos para cuando llegue.", ""],
  ["Lo que hoy cuesta, mañana es experiencia.", ""],
  ["Si el día viene torcido, enderezalo con una buena tarea terminada.", ""],
  ["Hay días de cosecha y días de siembra. Los dos son trabajo.", ""],
  ["La constancia le gana al talento que no se entrena.", ""],
  ["Mirar el horizonte ayuda, pero los pasos se dan de a uno.", ""],
  ["Hacé hoy lo que tu yo de mañana te va a agradecer.", ""],
  ["Lo importante no es no caerse del caballo, es volver a subirse.", ""],
  ["Una sonrisa en la balanza no cambia los kilos, pero cambia el día.", ""],
  ["Detrás de cada camión que sale hay un equipo que lo hizo posible.", ""],
  ["El esfuerzo de hoy es la tranquilidad de fin de mes.", ""],
  ["Cuando el trabajo tiene sentido, el día rinde el doble.", ""],
  ["Que no te gane la rutina: mirá el campo de nuevo, siempre hay algo para mejorar.", ""],
  ["El orgullo de un buen trabajo no se compra: se gana.", ""],
  ["Paciencia de ganadero, empuje de consignatario, prolijidad de administrativo. Esa es la receta.", ""],
  ["Mañana habrá otra feria; hoy hay que hacer bien esta.", ""],
  ["Las grandes empresas se hacen con gente que cuida las cosas chicas.", ""],
  ["Si hoy cuesta arrancar, empezá por un mate y una lista.", ""],
  ["Todo suma: la llamada, la planilla, el saludo, la carga.", ""]
];

// Mensajes según el día (los usa app.js). {nombre}, {lugar}, {mm}, {min}, {max} se reemplazan.
window.DW_MENSAJES = {
  remateHoy: ["Hoy hay remate en {lugar}. ¡A romperla, equipo!", "Día de remate en {lugar}: cada lote cuenta. ¡Vamos!"],
  remateManana: ["Mañana hay remate en {lugar}: hoy se prepara, mañana se luce."],
  lluvia: ["Cayeron {mm} mm. El campo agradece.", "Llovió {mm} mm: buen día para el pasto y para las planillas."],
  helada: ["Hoy amanece con {min}°: abrigarse y a darle."],
  calor: ["Se vienen {max}°: agua fresca para la hacienda y para el equipo."],
  lunes: ["Arrancamos la semana. Que sea una buena tropa de días."],
  viernes: ["Viernes: último empujón y a disfrutar el finde."],
  cumple: ["¡Hoy cumple {nombre}! 🎂 Que no falte el saludo."]
};
